### PR TITLE
Add method that allows user to specify `DataDir` directly

### PR DESCRIPTION
**Pull request by Luoxin**
Add a method that allows users to directly specify `DataDir`, simplifying the call path when users only want to change the `DataDir` value

### CODE REVIEW

**Comment by Luoxin** [comment]
https://github.com/EchoVault/EchoVault/issues/98

**Review by kelvinmwinuka — CHANGES_REQUESTED** [review]
@Luoxin 

What's the benefit of this change over using `WithConfig` in the following manner?

```go
config := echovault.DefaultConfig()
config.DataDir = "./data"
cache, err := echovault.NewEchoVault(echovault.WithConfig(config))
if err != nil {
  log.Fatal(err)
}
```

I think it's an interesting idea to provide an option like this for editing config. However, for consistency, we would have to provide this for all other configurable values as well, as users will expect them.

If you'd like to go this route, I'd recommend you create these options for all the config options and add them to the PR. We should also move all these options to the `echovault/config.go` file.

**Comment by Luoxin** [comment]
The user can complete the operation of the `NewEChovault` instead of adding a lot of lines directly through the line of` Withxxx`

I will make some modifications according to your suggestions.

**Comment by Luoxin** [comment]
I completed the method according to the existing fields in `config.Config`, with special handling for `bool` type data, which is considered `true` when no `bool` type value is passed in.

**Review by kelvinmwinuka — APPROVED** [review]
Looks good!

**Pull request merged**
